services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - '${MARIADB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - backend

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - '${PHPMYADMIN_MARIADB_PORT:-8081}:80'
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:

volumes:
  mariadb-data:
